# Testing CRUD functionality for Pokemon-Teams API

@base=http://127.0.0.1:5000/api/v1


### All Pokedex entries
GET {{base}}/pokedex/ HTTP/1.1
Content-Type: application/json


### Sprites for charizard (all forms)
GET {{base}}/sprites/6 HTTP/1.1
Content-Type: application/json


### All teams
GET {{base}}/teams HTTP/1.1
Content-Type: application/json


### Get a team
GET {{base}}/teams/1 HTTP/1.1
Content-Type: application/json


### Create a team with members [scyther]
POST {{base}}/teams HTTP/1.1
Content-Type: application/json

{
  "label": "TEST CREATE",
  "members": [
    {
      "dex_id": 764,
      "sprite_id": 1036,
      "gender": "M",
      "level": 50,
      "nickname": "CREATED",
      "slot": 1,
      "shiny": false
    }
  ]
}


### TODO: Update a team
PUT {{base}}/teams/2 HTTP/1.1
Content-Type: application/json

{
  "label": "UPDATED!",
  "members": [
    {
      "member_id": 123,
      "dex_id": 123,
      "sprite_id": 123,
      "gender": "M",
      "level": 50,
      "nickname": "",
      "shiny": false
    }
  ]
}


### Delete a team
DELETE {{base}}/teams/15 HTTP/1.1
Content-Type: application/json

