# Test hitting API
#
# API reference: https://pokeapi.co/docs/v2

@base=https://pokeapi.co/api/v2


### Get a single pokemon
GET {{base}}/pokemon/ditto HTTP/1.1
Content-Type: application/json


### Get all of generation 1
GET {{base}}/pokemon?limit=151&offset=0 HTTP/1.1
Content-Type: application/json
